services:
  wireshark:
    image: linuxserver/wireshark:3.4.13
    container_name: wireshark
    hostname: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
#    ports:
#      - 3000:3000 #optional
    restart: unless-stopped


